export const ActionTypes = {
  LOG_USER_IN: "LOG_USER_IN",
  LOG_USER_OUT: "LOG_USER_OUT",

  TOGGLE_GENERATE_DATABASE_TOKEN_DIALOG: "TOGGLE_GENERATE_DATABASE_TOKEN_DIALOG",
  GENERATE_DATABASE_TOKEN: "GENERATE_DATABASE_TOKEN",
  ERROR_GENERATE_DATABASE_TOKEN: "ERROR_GENERATE_DATABASE_TOKEN",

  UPDATE_USER_EMAIL: "UPDATE_USER_EMAIL",
  UPDATE_USER_PASSWORD: "UPDATE_USER_PASSWORD",
  CLEAR_ALL_STATE_AT_LOGOUT: "CLEAR_ALL_STATE_AT_LOGOUT",
  STORE_TABLE_DATA_FOR_EXPORT: "STORE_TABLE_DATA_FOR_EXPORT",
  CLEAR_TABLE_DATA_FOR_EXPORT: "CLEAR_TABLE_DATA_FOR_EXPORT",
  
  //**************************************************************//
  // FETCH STUDENTS DATA Action Types
  GET_STUDENTS_BY_DATE: "GET_STUDENTS_BY_DATE",
  GET_STUDENTS_BY_COURSE_NAME_AND_CAREER: "GET_STUDENTS_BY_COURSE_NAME_AND_CAREER",

  //**************************************************************//
  // Courses MODULE 1 Presence Data Action Types
  GET_COURSE_PRESENCE: 'GET_COURSE_PRESENCE',

  //**************************************************************//
  // Courses MODULE 1 Action Types
  GET_COURSES_MODULE_1: "GET_COURSES_MODULE_1",
  ERROR_GET_COURSES_MODULE_1: "ERROR_GET_COURSES_MODULE_1",
  ADD_COURSE_MODULE_1: "ADD_COURSE_MODULE_1",
  ERROR_ADD_COURSE_MODULE_1: "ERROR_ADD_COURSE_MODULE_1",
  UPDATE_COURSE_MODULE_1_STATE: "UPDATE_COURSE_MODULE_1_STATE",
  ERROR_UPDATE_COURSE_MODULE_1_STATE: "ERROR_UPDATE_COURSE_MODULE_1_STATE",
  CHANGE_COURSE_MODULE_1: "CHANGE_COURSE_MODULE_1",
  ERROR_CHANGE_COURSE_MODULE_1: "ERROR_CHANGE_COURSE_MODULE_1",
  DELETE_COURSE_MODULE_1: "DELETE_COURSE_MODULE_1",
  ERROR_DELETE_COURSE_MODULE_1: "ERROR_DELETE_COURSE_MODULE_1",
  CLEAR_COURSES_MODULE_1: "CLEAR_COURSES_MODULE_1",
  CLEAR_COURSES_MODULE_1_SERVER_RESPONSE: "CLEAR_COURSES_MODULE_1_SERVER_RESPONSE",

  //**************************************************************//
  // Courses MODULE 2 Action Types
  GET_COURSES_MODULE_2: "GET_COURSES_MODULE_2",
  ERROR_GET_COURSES_MODULE_2: "ERROR_GET_COURSES_MODULE_2",
  ADD_COURSE_MODULE_2: "ADD_COURSE_MODULE_2",
  ERROR_ADD_COURSE_MODULE_2: "ERROR_ADD_COURSE_MODULE_2",
  UPDATE_COURSE_MODULE_2_STATE: "UPDATE_COURSE_MODULE_2_STATE",
  ERROR_UPDATE_COURSE_MODULE_2_STATE: "ERROR_UPDATE_COURSE_MODULE_2_STATE",
  CHANGE_COURSE_MODULE_2: "CHANGE_COURSE_MODULE_2",
  ERROR_CHANGE_COURSE_MODULE_2: "ERROR_CHANGE_COURSE_MODULE_2",
  DELETE_COURSE_MODULE_2: "DELETE_COURSE_MODULE_2",
  ERROR_DELETE_COURSE_MODULE_2: "ERROR_DELETE_COURSE_MODULE_2",
  CLEAR_COURSES_MODULE_2: "CLEAR_COURSES_MODULE_2",
  CLEAR_COURSES_MODULE_2_SERVER_RESPONSE: "CLEAR_COURSES_MODULE_2_SERVER_RESPONSE",

  //**************************************************************//
  // Unsubscribe / Remove Student Action Types
  GET_STUDENT_DATA_FOR_UNSUBSCRIBE_OR_REMOVE: "GET_STUDENT_DATA_FOR_UNSUBSCRIBE_OR_REMOVE",
  STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
  UNSUBSCRIBED_OR_REMOVED_STUDENT: "UNSUBSCRIBED_OR_REMOVED_STUDENT",
  STUDENT_NOT_UNSUBSCRIBED_OR_REMOVED: "STUDENT_NOT_UNSUBSCRIBED_OR_REMOVED",
  
  //**************************************************************//
  // WebPages Data Manipulation
  //*** COURSES PAGE DATA ***//
  GET_COURSES_PAGE_DATA: "GET_COURSES_PAGE_DATA",
  ERROR_GET_COURSES_PAGE_DATA: "ERROR_GET_COURSES_PAGE_DATA",
  UPDATE_COURSES_PAGE_DATA: "UPDATE_COURSES_PAGE_DATA",
  ERROR_UPDATE_COURSES_PAGE_DATA: "ERROR_UPDATE_COURSES_PAGE_DATA",
  ADD_LINK_WORDS_COURSES_PAGE: "ADD_LINK_WORDS_COURSES_PAGE",
  REMOVE_LINK_WORDS_COURSES_PAGE: "REMOVE_LINK_WORDS_COURSES_PAGE",
  CLEAR_COURSES_PAGE_DATA_STATE: "CLEAR_COURSES_PAGE_DATA_STATE", 
  //*** COURSE PRESENCE DATA ***//
  GET_COURSE_PRESENCE_PAGE_DATA: "GET_COURSE_PRESENCE_PAGE_DATA",
  ERROR_GET_COURSE_PRESENCE_PAGE_DATA: "ERROR_GET_COURSE_PRESENCE_PAGE_DATA",
  UPDATE_COURSE_PRESENCE_PAGE_DATA: "UPDATE_COURSE_PRESENCE_PAGE_DATA",
  ERROR_UPDATE_COURSE_PRESENCE_PAGE_DATA: "ERROR_UPDATE_COURSE_PRESENCE_PAGE_DATA",
  ADD_LINK_WORDS_COURSE_PRESENCE_PAGE: "ADD_LINK_WORDS_COURSE_PRESENCE_PAGE",
  REMOVE_LINK_WORDS_COURSE_PRESENCE_PAGE: "REMOVE_LINK_WORDS_COURSE_PRESENCE_PAGE",
  CLEAR_COURSE_PRESENCE_PAGE_STATE: "CLEAR_COURSE_PRESENCE_PAGE_STATE", 
  //*** HEADER FOOTER DATA ***//
  GET_HEADER_FOOTER_DATA: "GET_HEADER_FOOTER_DATA",
  ERROR_GET_HEADER_FOOTER_DATA: "ERROR_GET_HEADER_FOOTER_DATA",
  UPDATE_HEADER_FOOTER_DATA: "UPDATE_HEADER_FOOTER_DATA",
  ERROR_UPDATE_HEADER_FOOTER_DATA: "ERROR_UPDATE_HEADER_FOOTER_DATA",
  ADD_LINK_WORDS_HEADER_FOOTER: "ADD_LINK_WORDS_HEADER_FOOTER",
  REMOVE_LINK_WORDS_HEADER_FOOTER: "REMOVE_LINK_WORDS_HEADER_FOOTER",
  CLEAR_HEADER_FOOTER_DATA_STATE: "CLEAR_HEADER_FOOTER_DATA_STATE",
  //** REGISTRATION FORM ALERTS **//
  GET_REGISTRATION_FORM_ALERTS: "GET_REGISTRATION_FORM_ALERTS",
  ERROR_GET_REGISTRATION_FORM_ALERTS: "ERROR_GET_REGISTRATION_FORM_ALERTS",
  UPDATE_REGISTRATION_FORM_ALERTS: "UPDATE_REGISTRATION_FORM_ALERTS",
  ERROR_UPDATE_REGISTRATION_FORM_ALERTS: "ERROR_UPDATE_REGISTRATION_FORM_ALERTS",
  CLEAR_REGISTRATION_FORM_ALERTS_STATE: "CLEAR_REGISTRATION_FORM_ALERTS_STATE",

  //**************************************************************//
  // Dashboard User Accounts
  GET_DASHBOARD_USERS: 'GET_DASHBOARD_USERS',
  ERROR_GET_DASHBOARD_USERS: 'ERROR_GET_DASHBOARD_USERS',
  ADD_DASHBOARD_USER: 'ADD_DASHBOARD_USER',
  ERROR_ADD_DASHBOARD_USER: "ERROR_ADD_DASHBOARD_USER",
  UPDATE_DASHBOARD_USER: 'UPDATE_DASHBOARD_USER',
  ERROR_UPDATE_DASHBOARD_USER: 'ERROR_UPDATE_DASHBOARD_USER',
  DELETE_DASHBOARD_USER: 'DELETE_DASHBOARD_USER',
  ERROR_DELETE_DASHBOARD_USER: 'ERROR_DELETE_DASHBOARD_USER',
  CLEAR_DASHBOARD_USER_SERVER_RESPONSE: "CLEAR_DASHBOARD_USER_SERVER_RESPONSE",

  //**************************************************************//
  // Email Confirmation Registration
  SUCCESS_GET_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE: "SUCCESS_GET_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE",
  ERROR_GET_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE: "ERROR_GET_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE",
  SUCCESS_UPDATE_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE: "_SUCCESS_UPDATE_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE",
  ERROR_UPDATE_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE: "ERROR_UPDATE_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE",
  SUCCESS_SEND_TEST_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE: "SUCCESS_SEND_TEST_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE",
  ERROR_SEND_TEST_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE: "ERROR_SEND_TEST_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE",
  CLEAR_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE_STATE: "CLEAR_EMAIL_CONFIRMATION_REGISTRATION_TEMPLATE_STATE",
  CLEAR_SERVER_MESSAGE_RESPONSE: "CLEAR_SERVER_MESSAGE_RESPONSE",

  //**************************************************************//
  // Email 3 Days After Registration Employee
  SUCCESS_GET_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE: "SUCCESS_GET_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE",
  ERROR_GET_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE: "ERROR_GET_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE",
  SUCCESS_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE: "_SUCCESS_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE",
  ERROR_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE: "ERROR_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE",
  SUCCESS_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE: "SUCCESS_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE",
  ERROR_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE: "ERROR_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE",
  CLEAR_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE_STATE: "CLEAR_EMAIL_3DAYS_AFTER_REGISTRATION_EMPLOYEE_TEMPLATE_STATE",

  //**************************************************************//
  // Email 3 Days After Registration Company
  SUCCESS_GET_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE: "SUCCESS_GET_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE",
  ERROR_GET_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE: "ERROR_GET_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE",
  SUCCESS_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE: "_SUCCESS_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE",
  ERROR_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE: "ERROR_UPDATE_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE",
  SUCCESS_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE: "SUCCESS_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE",
  ERROR_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE: "ERROR_SEND_TEST_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE",
  CLEAR_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE_STATE: "CLEAR_EMAIL_3DAYS_AFTER_REGISTRATION_COMPANY_TEMPLATE_STATE",

  //**************************************************************//
  // Email Reminder 7 Days
  GET_EMAIL_REMINDER_7DAYS: "GET_EMAIL_REMINDER_7DAYS",
  CHANGE_EMAIL_REMINDER_7DAYS: "CHANGE_EMAIL_REMINDER_7DAYS",
  ERROR_EMAIL_REMINDER_7DAYS: "ERROR_EMAIL_REMINDER_7DAYS",
  SEND_TEST_EMAIL_REMINDER_7_DAYS: "SEND_TEST_EMAIL_REMINDER_7_DAYS",
  ERROR_SEND_TEST_EMAIL_REMINDER_7_DAYS: "ERROR_SEND_TEST_EMAIL_REMINDER_7_DAYS",
  CLEAR_EMAIL_REMINDER_7_DAYS_STATE: "CLEAR_EMAIL_REMINDER_7_DAYS_STATE",
  LINK_WORDS_EMAIL_REMINDER_7_DAYS: 'LINK_WORDS_EMAIL_REMINDER_7_DAYS',

  //**************************************************************//
  // Email Reminder 1 Day
  GET_EMAIL_REMINDER_1DAY: "GET_EMAIL_REMINDER_1DAY",
  CHANGE_EMAIL_REMINDER_1DAY: "CHANGE_EMAIL_REMINDER_1DAY",
  ERROR_EMAIL_REMINDER_1DAY: "ERROR_EMAIL_REMINDER_1DAY",
  SEND_TEST_EMAIL_REMINDER_1_DAY: "SEND_TEST_EMAIL_REMINDER_1_DAY",
  ERROR_SEND_TEST_EMAIL_REMINDER_1_DAY: "ERROR_SEND_TEST_EMAIL_REMINDER_1_DAY",
  CLEAR_EMAIL_REMINDER_1_DAY_STATE: "CLEAR_EMAIL_REMINDER_1_DAY_STATE",
  LINK_WORDS_EMAIL_REMINDER_1_DAY: 'LINK_WORDS_EMAIL_REMINDER_1_DAY',

  //**************************************************************//
  // Email Reminder 1 Hour
  GET_EMAIL_REMINDER_1HOUR: "GET_EMAIL_REMINDER_1HOUR",
  CHANGE_EMAIL_REMINDER_1HOUR: "CHANGE_EMAIL_REMINDER_1HOUR",
  ERROR_EMAIL_REMINDER_1HOUR: "ERROR_EMAIL_REMINDER_1HOUR",
  SEND_TEST_EMAIL_REMINDER_1_HOUR: "SEND_TEST_EMAIL_REMINDER_1_HOUR",
  ERROR_SEND_TEST_EMAIL_REMINDER_1_HOUR: "ERROR_SEND_TEST_EMAIL_REMINDER_1_HOUR",
  CLEAR_EMAIL_REMINDER_1_HOUR_STATE: "CLEAR_EMAIL_REMINDER_1_HOUR_STATE",
  ADD_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_1: 'ADD_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_1',
  ADD_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_2: 'ADD_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_2',
  REMOVE_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_1: 'REMOVE_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_1',
  REMOVE_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_2: 'REMOVE_LINK_WORDS_EMAIL_REMINDER_1_HOUR_PAR_2'
}