export const appRoutes = {
  sectiune_admin: '/sectiune-admin',
  pagina_cursuri: '/editare-pagina-cursuri',
  headerFooter: '/editare-header-footer',
  formular_inscriere: '/editare-formular-inscriere',
  confirmare_prezenta: '/editare-confirmare-prezenta',
  confirmare_prezenta_curs_in_prezent: '/confirmare-prezenta-curs-in-prezent',
  confirmare_prezenta_curs_in_trecut_viitor: '/confirmare-prezenta-curs-in-trecut-viitor',
  confirmare_prezenta_acces_curs_zoom: '/confirmare-prezenta-acces-curs-zoom',
  cursuri_modul1: '/cursuri-modul1',
  cursuri_modul2: '/cursuri-modul2',
  cauta_cursant: '/cauta-cursant',
  total_cursanti: '/total-cursanti',
  cursanti_per_curs: '/cursanti-per-curs',
  cursanti_prezenti: '/cursanti-prezenti',
  inscriere_cursanti_modul2: '/inscriere-cursanti-modul2',
  dezabonare_cursanti: '/dezabonare-cursanti',
  email_registration: '/email-confirmare-inscriere',
  email_reminder_7days: '/email-reminder-7zile',
  email_reminder_1day: '/email-reminder-1zi',
  email_reminder_1hour: '/email-reminder-1ora',
  email_voucher_4hours: '/email-voucher-4ore',
  email_voucher_18hours: '/email-voucher-18ore',
  email_3days_after_registration_employee: "/email-3-zile-inscriere-angajat",
  email_3days_after_registration_company: '/email-3-zile-inscriere-antreprenor'
}